import type { Metadata } from "next";
import "./globals.css";
import BlogHeader from "../components/layouts/BlogHeader";
import BlogFooter from "../components/layouts/BlogFooter";
import { ModeThemeProvider } from "@/provider/ModeThemeProvider";

export const metadata: Metadata = {
  title: "Hyeongyu's blog",
  description: "Generated by create next app",
};

export default function RootLayout({children, }: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="ko" suppressHydrationWarning>
      <body className="px-5">
        <ModeThemeProvider>
          <BlogHeader />
            {children}
          <BlogFooter />
        </ModeThemeProvider>
      </body>
    </html>
  );
}
